name: Deploy to Vercel

on:
  push:
    branches:
      - main  # 當推到 main 分支時觸發 部署正式站

  pull_request:
    branches:
      - main  # PR 時建立預覽部署
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install
        # 新增：跑 ESLint 檢查
      - name: Run ESLint
        run: npm run lint

      # 新增：跑 Vitest 單元測試
      - name: Run Vitest
        run: npm run test

      # 如果上面都通過才會繼續 build & deploy
      - name: Build project
        run: npm run build

      # 分支判斷：PR 時預覽部署，main 時正式部署
      - name: Deploy to Vercel (Preview for PR)
        if: github.event_name == 'pull_request'
        run: npx vercel --token=${{ secrets.VERCEL_TOKEN }}

      - name: Deploy to Vercel (Production)
        if: github.ref == 'refs/heads/main'
        run: npx vercel --prod --token=${{ secrets.VERCEL_TOKEN }}